# Log4j2 configuration
# Níveis: TRACE => DEBUG => INFO => WARN => ERROR => FATAL

appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = log4j2.log
appender.file.append = true
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1} - %m%n

rootLogger.level = info
rootLogger.appenderRefs = file
rootLogger.appenderRef.file.ref = FileAppender

logger.hibernate.name = org.hibernate
logger.hibernate.level = warn

logger.hibernate_sql.name = org.hibernate.SQL
logger.hibernate_sql.level = debug

logger.hibernate_bind.name = org.hibernate.orm.jdbc.bind
logger.hibernate_bind.level = trace